#!/bin/bash

source mysql.handyman.cfg

$(mysql -u${sys_user} -p ${db_name} <<EOF
# ### BEGIN SEED
# Clerks
INSERT INTO clerks (login, first_name, last_name, password)
VALUES ("arta", "Art", "Anderson", "arta");
INSERT INTO clerks (login, first_name, last_name, password)
VALUES ("bobb", "Bob", "Baker", "bobb");
INSERT INTO clerks (login, first_name, last_name, password)
VALUES ("cabc", "Cab", "Calloway", "cabc");
INSERT INTO clerks (login, first_name, last_name, password)
VALUES ("dond", "Don", "Douglas", "dond");
INSERT INTO clerks (login, first_name, last_name, password)
VALUES ("emae", "Ema", "East", "emae");
INSERT INTO clerks (login, first_name, last_name, password)
VALUES ("fayf", "Fay", "Franklin", "fayf");
# Customers
INSERT INTO customers (email, first_name, last_name, password, address, work_phone_cc, work_phone_number, home_phone_cc, home_phone_number)
VALUES ("tom@tommorrow.com", "Tom", "Tommorrow", "tom", "Future Land", "1", "9194941000", "1", "9194942000");
INSERT INTO customers (email, first_name, last_name, password, address, work_phone_cc, work_phone_number, home_phone_cc, home_phone_number)
VALUES ("unicron@cybertron.com", "Unicron", "Primus", "unicaron", "The Planet Cybertron", "1", "9194943000", "1", "9194944000");
INSERT INTO customers (email, first_name, last_name, password, address, work_phone_cc, work_phone_number, home_phone_cc, home_phone_number)
VALUES ("vincent@vega.com", "Vincent", "Vega", "vincent", "The House of Wallace", "1", "9194945000", "1", "9194946000");
INSERT INTO customers (email, first_name, last_name, password, address, work_phone_cc, work_phone_number, home_phone_cc, home_phone_number)
VALUES ("xavier@xmen.com", "Charles", "Xavier", "xavier", "Professor Xavier's School for the Gifted", "1", "1234567890", "1", "2345678901");
INSERT INTO customers (email, first_name, last_name, password, address, work_phone_cc, work_phone_number, home_phone_cc, home_phone_number)
VALUES ("yolandi@derantwood.com", "Yolandi", "Visser", "yolandi", "District 9", "27", "111234567", "27", "821234567");
INSERT INTO customers (email, first_name, last_name, password, address, work_phone_cc, work_phone_number, home_phone_cc, home_phone_number)
VALUES ("zorro@swords.com", "Zorro", "Zoroaster", "zorro", "Parts Unknown", "52", "12345678", "52", "23456789");
INSERT INTO customers (email, first_name, last_name, password, address, work_phone_cc, work_phone_number, home_phone_cc, home_phone_number)
VALUES ("ta@gatech.edu", "TA", "TA", "ta", "Parts Unknown", "52", "12345678", "52", "23456789");
# Categories
INSERT INTO categories (category, has_accessories)
VALUES("Hand Tools", FALSE);
INSERT INTO categories (category, has_accessories)
VALUES("Construction Equipment", FALSE);
INSERT INTO categories (category, has_accessories)
VALUES("Power Tools", TRUE);
# Tools
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Hammer", "Normal Hammer", 1.00, 1.00, 1.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Claw Hammer", "A hammer with a claw", 1.00, 1.25, 1.25, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Jackhammer", "Gas powered and big", 101.00, 100.00, 1000.00, 2);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Planer", "Planes wood", 5.00, 50.00, 500.00, 3);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Sawzall", "Sawzall and accessories", 5.00, 50.00, 250.00, 3);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Wrench", "Normal Wrench", 1.00, 1.00, 1.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Plumber Wrench", "An adjustable wrench", 1.00, 1.25, 1.25, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Plumb Line", "Construction-grade plumb line", 101.00, 100.00, 1000.00, 2);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Lathe", "Can fashion weapons", 5.00, 50.00, 500.00, 3);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Belt Sander", "Powerful sander, needs paper", 5.00, 50.00, 250.00, 3);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Pry Bar Set (3)", "Set of 3 easy to use pry bars", 2.00, 5.00, 20.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Pry Bar, Large", "Large 2 handed pry bar", 4.00, 7.00, 40.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Pry Bar, Huge", "Huge 4 handed pry bar", 8.00, 10.00, 60.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Pliers, Needle nose", "Pliers with needle nose ends, padded grips", 1.00, 2.00, 10.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Pliers, 4 in", "Pliers with 4 in padded grips", 1.00, 2.00, 6.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Pliers, 5 in", "Pliers with 5 in padded grips", 1.50, 2.50, 8.50, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Pliers, 6 in", "Pliers with 6 in padded grips", 1.60, 2.60, 8.60, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Pliers, 7 in", "Pliers with 7 in padded grips", 1.70, 2.70, 8.70, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Pliers, 8 in", "Pliers with 8 in padded grips", 1.80, 2.80, 8.80, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Pliers, 9 in", "Pliers with 9 in padded grips", 1.90, 2.90, 8.90, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Pliers, 10 in", "Pliers with 10 in padded grips", 2.00, 3.00, 9.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Lock Pliers, Needle nose", "Lock Pliers with needle nose ends, padded grips", 1.00, 2.00, 10.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Lock Pliers, 4 in", "Lock Pliers with 4 in padded grips", 1.00, 2.00, 8.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Lock Pliers, 5 in", "Lock Pliers with 5 in padded grips", 1.50, 2.50, 8.50, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Lock Pliers, 6 in", "Lock Pliers with 6 in padded grips", 1.60, 2.60, 8.60, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Lock Pliers, 7 in", "Lock Pliers with 7 in padded grips", 1.70, 2.70, 8.70, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Lock Pliers, 8 in", "Lock Pliers with 8 in padded grips", 1.80, 2.80, 8.80, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Lock Pliers, 9 in", "Lock Pliers with 9 in padded grips", 1.90, 2.90, 8.90, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Lock Pliers, 10 in", "Lock Pliers with 10 in padded grips", 2.00, 3.00, 9.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Adjustable Wrench, 6 in", "Fully adjustable wrench with 6 in padded grip", 2.00, 3.00, 9.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Adjustable Wrench, 8 in", "Fully adjustable wrench with 8 in padded grip", 2.00, 3.00, 9.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Adjustable Wrench, 10 in", "Fully adjustable wrench with 10 in padded grip", 2.00, 3.00, 9.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Adjustable Wrench, 12 in", "Fully adjustable wrench with 12 in padded grip", 2.00, 3.00, 9.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Adjustable Wrench, 14 in", "Fully adjustable wrench with 14 in padded grip", 2.00, 3.00, 9.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Adjustable Wrench, 16 in", "Fully adjustable wrench with 16 in padded grip", 2.00, 3.00, 9.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Hand saw, 14 in", "Hand saw, like for cutting wood, with 14 in blade", 2.00, 4.00, 14.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Hand saw, 18 in", "Hand saw, like for cutting wood, with 18 in blade", 2.50, 5.00, 18.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Hand saw, 22 in", "Hand saw, like for cutting wood, with 22 in blade", 3.00, 6.00, 22.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Hand saw, 26 in", "Hand saw, like for cutting wood, with 26 in blade", 3.50, 7.00, 26.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Hand saw, 30 in", "Hand saw, like for cutting wood, with 30 in blade", 4.00, 8.00, 30.00, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Sheet Metal Shears", "Powerful sheet metal cutting shears", 20.00, 10.00, 75.00, 3);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Angle Grinder", "Angle grinder with 7.5 Amp motor.", 20.00, 10.00, 75.00, 3);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Drill, mini", "Mini drill with 2.5 Amp motor.", 10.00, 5.00, 30.00, 3);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Drill", "Drill with 4.5 Amp motor.", 10.00, 5.00, 30.00, 3);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Dump Truck", "Dump truck... yep.", 1000.00, 100.00, 20000.00, 2);
# TOOL ACCESSORIES
INSERT INTO tool_accessories (tool_id, description)
SELECT tool_id, "Mitre box" FROM tools WHERE short_description = "Sawzall";
INSERT INTO tool_accessories (tool_id, description)
SELECT tool_id, "Extra blades" FROM tools WHERE short_description = "Sawzall";
INSERT INTO tool_accessories (tool_id, description)
VALUES(10, "Sandpaper");
SELECT tool_id, "Sandpaper" FROM tools WHERE short_description = "Belt Sander";
INSERT INTO tool_accessories (tool_id, description)
SELECT tool_id, "Cutoff disc" FROM tools WHERE short_description = "Angle Grinder";
INSERT INTO tool_accessories (tool_id, description)
SELECT tool_id, "Diamond grinding disc" FROM tools WHERE short_description = "Angle Grinder";
# RESERVATIONS
# Completed
INSERT INTO reservations (start_date, end_date, customer_id, clerk_id_pickup, clerk_id_dropoff, credit_card, expiration_date)
VALUES ('2016-01-01', '2016-01-10', 1, 1, 1, "VISA123", '2017-01-01');
INSERT INTO reservations (start_date, end_date, customer_id, clerk_id_pickup, clerk_id_dropoff, credit_card, expiration_date)
VALUES ('2016-05-01', '2016-06-10', 1, 1, 2, "AMEX5500", '2017-01-01');
# Started, not completed
INSERT INTO reservations (start_date, end_date, customer_id, clerk_id_pickup, credit_card, expiration_date)
VALUES ('2016-02-01', '2016-02-10', 2, 2, "MC456", '2017-01-01');
# Not started
INSERT INTO reservations (start_date, end_date, customer_id)
VALUES ('2016-03-01', '2016-03-10', 3);
# RESERVATIONS_TOOLS
INSERT INTO reservations_tools (reservation_id, tool_id)
VALUES (1, 1);
INSERT INTO reservations_tools (reservation_id, tool_id)
VALUES (1, 2);
INSERT INTO reservations_tools (reservation_id, tool_id)
VALUES (1, 3);
INSERT INTO reservations_tools (reservation_id, tool_id)
VALUES (2, 1);
INSERT INTO reservations_tools (reservation_id, tool_id)
VALUES (2, 2);
INSERT INTO reservations_tools (reservation_id, tool_id)
VALUES (3, 3);
INSERT INTO reservations_tools (reservation_id, tool_id)
VALUES (3, 4);
# SERVICE ORDERS
INSERT INTO service_orders (clerk_id, tool_id, start_date, end_date, est_cost)
VALUES (1, 5, '2016-01-01', '2016-03-20', 100.00);
# Required elements
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Tool 1", "As requested, tool 1", 1.11, 11.11, 111.11, 1);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Tool 2", "As requested, tool 2", 2.22, 22.22, 222.22, 2);
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Tool 3", "As requested, tool 3", 3.33, 33.33, 333.33, 3);
# Reservation 1
INSERT INTO reservations (start_date, end_date, customer_id, clerk_id_pickup, clerk_id_dropoff, credit_card, expiration_date)
VALUES ('2016-03-01', '2016-03-03', 7, 1, 2, "VISA777", '2017-01-01');
INSERT INTO reservations_tools (reservation_id, tool_id)
SELECT 5, tool_id FROM tools WHERE short_description = "Tool 1";
INSERT INTO reservations_tools (reservation_id, tool_id)
SELECT 5, tool_id FROM tools WHERE short_description = "Tool 3";
# Reservation 2
INSERT INTO reservations (start_date, end_date, customer_id)
VALUES ('2016-05-01', '2016-05-03', 7);
INSERT INTO reservations_tools (reservation_id, tool_id)
SELECT 6, tool_id FROM tools WHERE short_description = "Tool 2";
INSERT INTO reservations_tools (reservation_id, tool_id)
SELECT 6, tool_id FROM tools WHERE short_description = "Tool 3";
# Reservation 3
INSERT INTO reservations (start_date, end_date, customer_id)
VALUES ('2016-04-25', '2016-06-25', 7);
INSERT INTO reservations_tools (reservation_id, tool_id)
SELECT 7, tool_id FROM tools WHERE short_description = "Tool 3";
INSERT INTO service_orders (clerk_id, tool_id, start_date, end_date, est_cost)
SELECT 6, tool_id, '2016-02-01', '2016-02-02', 10.00 FROM tools WHERE short_description = "Tool 1";
INSERT INTO service_orders (clerk_id, tool_id, start_date, end_date, est_cost)
SELECT 1, tool_id, '2016-02-11', '2016-02-15', 10.00 FROM tools WHERE short_description = "Tool 1";
# ### END SEED
EOF
);