#!/bin/bash

source mysql.handyman.cfg

$(mysql -u${sys_user} -p ${db_name} <<EOF
# ### BEGIN SEED

# Clerks
INSERT INTO clerks (login, first_name, last_name, password)
VALUES ("arta", "Art", "Anderson", "arta");


INSERT INTO clerks (login, first_name, last_name, password)
VALUES ("bobb", "Bob", "Baker", "bobb");


INSERT INTO clerks (login, first_name, last_name, password)
VALUES ("cabc", "Cab", "Calloway", "cabc");

# Customers
INSERT INTO customers (email, first_name, last_name, password, address, work_phone_cc, work_phone_number, home_phone_cc, home_phone_number)
VALUES ("xavier@xmen.com", "Charles", "Xavier", "xavier", "Professor Xavier's School for the Gifted", "1", "1234567890", "1", "2345678901");

INSERT INTO customers (email, first_name, last_name, password, address, work_phone_cc, work_phone_number, home_phone_cc, home_phone_number)
VALUES ("yolandi@derantwood.com", "Yolandi", "Visser", "yolandi", "District 9", "27", "111234567", "27", "821234567");

INSERT INTO customers (email, first_name, last_name, password, address, work_phone_cc, work_phone_number, home_phone_cc, home_phone_number)
VALUES ("zorro@swords.com", "Zorro", "Zoroaster", "zorro", "Parts Unknown", "52", "12345678", "52", "23456789");

# Categories
INSERT INTO categories (category, has_accessories)
VALUES("Hand Tools", FALSE);

INSERT INTO categories (category, has_accessories)
VALUES("Construction Equipment", FALSE);

INSERT INTO categories (category, has_accessories)
VALUES("Power Tools", TRUE);

# Tools
INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Hammer", "Normal Hammer", 1.00, 1.00, 1.00, 1);

INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Claw Hammer", "A hammer with a claw", 1.00, 1.25, 1.25, 1);

INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Jackhammer", "Gas powered and big", 101.00, 100.00, 1000.00, 2);

INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Planer", "Planes wood", 5.00, 50.00, 500.00, 3);

INSERT INTO tools (short_description, full_description, deposit, day_price, original_price, category_id)
VALUES("Sawzall", "Sawzall and accessories", 5.00, 50.00, 250.00, 3);

# TOOL ACCESSORIES
INSERT INTO tool_accessories (tool_id, description)
VALUES(5, "Mitre box");

INSERT INTO tool_accessories (tool_id, description)
VALUES(5, "Extra blades");

# RESERVATIONS
# Completed
INSERT INTO reservations (start_date, end_date, customer_id, clerk_id_pickup, clerk_id_dropoff, credit_card, expiration_date)
VALUES ('2016-01-01', '2016-01-10', 1, 1, 1, "VISA123", '2017-01-01');

# Started, not completed
INSERT INTO reservations (start_date, end_date, customer_id, clerk_id_pickup, credit_card, expiration_date)
VALUES ('2016-02-01', '2016-02-10', 2, 2, "MC456", '2017-01-01');

# Not started
INSERT INTO reservations (start_date, end_date, customer_id, credit_card, expiration_date)
VALUES ('2016-03-01', '2016-03-10', 3, "VISA777", '2017-01-01');

# RESERVATIONS_TOOLS
INSERT INTO reservations_tools (reservation_id, tool_id) 
VALUES (1, 1);

INSERT INTO reservations_tools (reservation_id, tool_id) 
VALUES (1, 2);

INSERT INTO reservations_tools (reservation_id, tool_id) 
VALUES (1, 3);

INSERT INTO reservations_tools (reservation_id, tool_id) 
VALUES (2, 1);

INSERT INTO reservations_tools (reservation_id, tool_id) 
VALUES (2, 2);

INSERT INTO reservations_tools (reservation_id, tool_id) 
VALUES (3, 3);

INSERT INTO reservations_tools (reservation_id, tool_id) 
VALUES (3, 4);

# SERVICE ORDERS
INSERT INTO service_orders (clerk_id, tool_id, start_date, end_date, est_cost) 
VALUES (1, 5, '2016-01-01', '2017-12-31', 100.00);

# ### END SEED

EOF
);
